Sprint 18 gw
ImagingDataCommons/IDC-Common pull request #180
Opened 2021-02-03 21:58 UTC by G-White-ISB

Adapt solr querying to handle retrieval of rows with limit, offset. Not actually used yet, but this PR needs to be included with PR on IDC-WebApp.

2021-02-03 23:22 UTC, s-paquette requested changes

2021-02-03 23:22 UTC, s-paquette commented on idc_collections/collex_metadata_utils.py
> +                'limit': record_limit,
If you do this to the facet counting, the facets will ONLY show counts for those 2000 records. Facet counting should never be limited or offset--only record retrieval. While it's true that counts_only will ignore and override this value, it's still a potentially invisible bug I'd rather avoid.

2021-02-03 23:22 UTC, s-paquette commented on solr_helpers/__init__.py
>                  'missing': True,
As above: don't apply a limit to facets, or it will only give you counts for that many records, which isn't what we want.

2021-02-04 16:58 UTC, G-White-ISB commented
Ok I'm going to cancel request this PR and change the WebApp PR so it works with current master of IDC-Common

2021-02-04 16:58 UTC, closed without merging